### ISSUE TITLE
Formatting includes inadvertent mix of tabs and spaces

### ISSUE THREAD

**Issue by catskul** [ajakhotia/units#1]
It appears that _"tabs for indent, spaces for alignment"_ format strategy was intended, however in some locations tabs are used for alignment and on other, spaces. ; )

**Comment by ajakhotia** [comment]
Aah, damn clion's auto formatting tool.

**Comment by ajakhotia** [comment]
Fixed in revision hash 8bd8a2e0238c99e85c959db69344271f74f4fc1e
